# Ruby CircleCI 2.0 configuration file
#
# Check https://circleci.com/docs/2.0/language-ruby/ for more details
#
version: 2
jobs:
  build:
    docker:
      # specify the version you desire here
       - image: circleci/ruby:2.7.5-node-browsers
         environment:
           RAILS_ENV: test
       - image: circleci/redis:4

    working_directory: ~/repo

    steps:
      - checkout

      # Download and cache dependencies
      - restore_cache:
          keys:
          - v3-dependencies-{{ checksum "Gemfile.lock" }}
          # fallback to using the latest cache if no exact match is found
          - v3-dependencies-

      - run:
          name: install dependencies
          command: |
            gem install bundler -v 2.4.22
            bundle install --jobs=4 --retry=3 --path vendor/bundle

      - save_cache:
          paths:
            - ./vendor/bundle
          key: v3-dependencies-{{ checksum "Gemfile.lock" }}

      # Database setup
      - run: cp spec/test_app/config/api-keys.yml.example spec/test_app/config/api-keys.yml
      - run: cp spec/test_app/config/redis.yml-example spec/test_app/config/redis.yml
      - run: cd spec/test_app && bundle exec rake db:create db:migrate db:schema:load

      - run:
          name: flakey specs
          command: |
            mkdir /tmp/test-results
            bundle exec rspec --tag "flakey" \
                              --format documentation \
                              --format RspecJunitFormatter \
                              --out /tmp/test-results/rspec.xml

      # run tests!
      - run:
          name: run tests
          command: |
            bundle exec rspec --tag "~flakey" --tag "~exclude_from_circle" --format progress \
                            --format RspecJunitFormatter \
                            --out /tmp/test-results/rspec.xml

      # collect reports
      - store_test_results:
          path: /tmp/test-results
      - store_artifacts:
          path: /tmp/test-results
          destination: test-results
