ruby_version: ruby-2.1.2
bundler_version: 1.6.2
environment:
  RAILS_LOG_LEVEL: '2'
coverage: true
timeout: 300
test_exclude_pattern:
- spec/flaky/*
notify:
- channel: email
  trigger-on: failed
  message: "Congratulations, testing of %repo%'s %branch% branch finished in %duration% with %error-count% error(s) and %passed-count% success(es)"
  recipients: committers
- channel: slack
  trigger-on: status-changed
  room: rubydevs
  team: Network for Good
  message: "@releasemanager Congratulations, testing of %repo%'s %branch% branch finished in %duration% with %error-count% error(s) and %passed-count% success(es)"